### ISSUE TITLE
connect to proxy

### ISSUE THREAD

**Issue by Yasin-Dev81** [firebolt55439/cors-proxy-heroku#1]
Hello
I deploy this code on heroku but I do not know how to connect to this proxy!
please guide me

**Comment by firebolt55439** [comment]
Honestly, this code was pretty much tailored towards a specific application I had, and is pretty awfully written (I wrote it quite a while back and just thought to upload it to Github later). 

I would *strongly* recommend going with this alternative: https://github.com/Rob--W/cors-anywhere. It is well-supported, well-documented, and very configurable. You can see documentation [here](https://elements.heroku.com/buttons/puzzleboss/cors-anywhere) and a full blog post tutorial [here](https://dev.to/imiebogodson/fixing-the-cors-error-by-hosting-your-own-proxy-on-heroku-3lcb).

**Comment by Yasin-Dev81** [comment]
thanks
